### ISSUE TITLE
Only use X11 on net.veloren.airshipper.yaml specification

### ISSUE THREAD

**Issue by marcelovbcfilho** [flathub/net.veloren.airshipper#10]
## What hapened

After downloading the game from Flathub, starting it and click play after downloaded the updated the game just crash.

## System information

![Screenshot from 2022-06-16 09-22-32](https://user-images.githubusercontent.com/51462138/174068725-d92f99f7-2d62-412f-9b64-fb01d5d5d928.png)

## Possible solution

After thinking for a while I remembered that I was using wayland, and that it is a little unstable yet so I opened Flatseal, removed the wayland socket and after restart the app it was working as expected. Maybe remove the wayland socket from ```net.veloren.airshipper.yaml``` and let only X11 while it is not working for everyone. If you said that this is a viable solution I can fix and open a pull request.

## Logs after the crash using wayland socket

```
[2m2022-06-16T12:19:03.623662Z[0m [32m INFO[0m [2mveloren_common_frontend[0m[2m:[0m Setup terminal and file logging. [3mpath[0m[2m=[0m"/home/marcelovbcfilho/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata/voxygen/logs" [3mfile[0m[2m=[0m"2022-06-16_voxygen.log"
[2m2022-06-16T12:19:03.623694Z[0m [32m INFO[0m [2mveloren_voxygen[0m[2m:[0m Using userdata dir at: /home/marcelovbcfilho/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata
[2m2022-06-16T12:19:03.623703Z[0m [32m INFO[0m [2mveloren_voxygen[0m[2m:[0m Using config dir at: /home/marcelovbcfilho/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata/voxygen
[2m2022-06-16T12:19:03.734537Z[0m [32m INFO[0m [2mveloren_common_assets[0m[2m:[0m Assets found path=/home/marcelovbcfilho/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/assets
[2m2022-06-16T12:19:03.754807Z[0m [31mERROR[0m [2msmithay_client_toolkit::window::concept_frame[0m[2m:[0m No font could be found    
[2m2022-06-16T12:19:03.869817Z[0m [32m INFO[0m [2mwgpu_core::instance[0m[2m:[0m Adapter Vulkan AdapterInfo { name: "AMD RADV RENOIR", vendor: 4098, device: 5686, device_type: IntegratedGpu }    
[2m2022-06-16T12:19:03.869855Z[0m [32m INFO[0m [2mwgpu_core::instance[0m[2m:[0m Adapter Vulkan AdapterInfo { name: "llvmpipe (LLVM 12.0.1, 256 bits)", vendor: 65541, device: 0, device_type: Cpu }    
[2m2022-06-16T12:19:03.869871Z[0m [32m INFO[0m [2mwgpu_core::instance[0m[2m:[0m Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 1650", vendor: 4318, device: 8089, device_type: DiscreteGpu }    
[2m2022-06-16T12:19:03.869898Z[0m [32m INFO[0m [2mveloren_voxygen::render::renderer[0m[2m:[0m graphics device #0 [3minfo.name[0m[2m=[0m"AMD RADV RENOIR" [3minfo.vendor[0m[2m=[0m4098 [3minfo.backend[0m[2m=[0mVulkan [3minfo.device[0m[2m=[0m5686 [3minfo.device_type[0m[2m=[0mIntegratedGpu
[2m2022-06-16T12:19:03.869906Z[0m [32m INFO[0m [2mveloren_voxygen::render::renderer[0m[2m:[0m graphics device #1 [3minfo.name[0m[2m=[0m"llvmpipe (LLVM 12.0.1, 256 bits)" [3minfo.vendor[0m[2m=[0m65541 [3minfo.backend[0m[2m=[0mVulkan [3minfo.device[0m[2m=[0m0 [3minfo.device_type[0m[2m=[0mCpu
[2m2022-06-16T12:19:03.869913Z[0m [32m INFO[0m [2mveloren_voxygen::render::renderer[0m[2m:[0m graphics device #2 [3minfo.name[0m[2m=[0m"NVIDIA GeForce GTX 1650" [3minfo.vendor[0m[2m=[0m4318 [3minfo.backend[0m[2m=[0mVulkan [3minfo.device[0m[2m=[0m8089 [3minfo.device_type[0m[2m=[0mDiscreteGpu
[2m2022-06-16T12:19:03.881043Z[0m [32m INFO[0m [2mwgpu_core::instance[0m[2m:[0m Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 1650", vendor: 4318, device: 8089, device_type: DiscreteGpu }    
[2m2022-06-16T12:19:03.881076Z[0m [32m INFO[0m [2mveloren_voxygen::render::renderer[0m[2m:[0m selected graphics device [3minfo.name[0m[2m=[0m"NVIDIA GeForce GTX 1650" [3minfo.vendor[0m[2m=[0m4318 [3minfo.backend[0m[2m=[0mVulkan [3minfo.device[0m[2m=[0m8089 [3minfo.device_type[0m[2m=[0mDiscreteGpu
[2m2022-06-16T12:19:03.881087Z[0m [33m WARN[0m [2mwgpu_core::instance[0m[2m:[0m The underlying API or device in use does not support enough features to be a fully compliant implementation of WebGPU. A subset of the features can still be used. If you are running this program on native and not in a browser and wish to limit the features you use to the supported subset, call Adapter::downlevel_properties or Device::downlevel_properties to get a listing of the features the current platform supports.    
[2m2022-06-16T12:19:03.882004Z[0m [32m INFO[0m [2mgfx_backend_vulkan[0m[2m:[0m 
GENERAL [Loader Message (0x0)] : Loading layer library libVkLayer_MESA_device_select.so
object info: (type: INSTANCE, hndl: 0x562f694dd210)
    
[2m2022-06-16T12:19:03.882022Z[0m [32m INFO[0m [2mgfx_backend_vulkan[0m[2m:[0m 
GENERAL [Loader Message (0x0)] : Failed to find vkGetDeviceProcAddr in layer libVkLayer_MESA_device_select.so
object info: (type: INSTANCE, hndl: 0x562f694dd210)
    
[2m2022-06-16T12:19:03.904393Z[0m [32m INFO[0m [2mwgpu_core::command::allocator[0m[2m:[0m Starting on (internal) thread ThreadId(1)    
[2m2022-06-16T12:19:03.904477Z[0m [32m INFO[0m [2mveloren_voxygen::render::renderer[0m[2m:[0m Using Bgra8Unorm as the swapchain format
[2m2022-06-16T12:19:03.904493Z[0m [33m WARN[0m [2mwgpu_core::device[0m[2m:[0m Surface does not support present mode: IMMEDIATE, falling back to FIFO    
[2m2022-06-16T12:19:03.905186Z[0m [31mERROR[0m [2mgfx_backend_vulkan::device[0m[2m:[0m Unexpected result - driver bug? ERROR_INITIALIZATION_FAILED    
[2m2022-06-16T12:19:04.062727Z[0m [31mERROR[0m [2mveloren_voxygen[0m[2m:[0m VOXYGEN HAS PANICKED

A critical error has occurred and Voxygen has been forced to terminate in an unusual manner. Details about the error can be found below.

> What should I do?

We need your help to fix this! You can help by contacting us and reporting this problem. To do this, open an issue on the Veloren issue tracker:

https://www.gitlab.com/veloren/veloren/issues/new

If you're on the Veloren community Discord server, we'd be grateful if you could also post a message in the #support channel.
            
> What should I include?

The error information below will be useful in finding and fixing the problem. Please include as much information about your setup and the events that led up to the panic as possible.
            
Voxygen has logged information about the problem (including this message) to the file /home/marcelovbcfilho/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata/voxygen/logs/2022-06-16_voxygen.log. Please include the contents of this file in your bug report.
            
> Error information

The information below is intended for developers and testers.

Panic Payload: "failed to configure swap chain on creation: Swapchain can't be created for an unknown reason"
PanicInfo: panicked at 'failed to configure swap chain on creation: Swapchain can't be created for an unknown reason', /root/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/a92b854/wgpu-core/src/device/mod.rs:4541:29
Game version: b12dc3b0 [2022-06-08]

Backtrace:
   0: veloren_voxygen::main::{{closure}}
             at /builds/veloren/veloren/voxygen/src/main.rs:139:13
   1: std::panicking::rust_panic_with_hook
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/panicking.rs:142:14
   6: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
   7: veloren_voxygen::render::renderer::Renderer::new
             at /builds/veloren/veloren/voxygen/src/render/renderer.rs:350:26
   8: veloren_voxygen::window::Window::new
             at /builds/veloren/veloren/voxygen/src/window.rs:429:24
   9: veloren_voxygen::main
             at /builds/veloren/veloren/voxygen/src/main.rs:245:42
  10: core::ops::function::FnOnce::call_once
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/ops/function.rs:248:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/sys_common/backtrace.rs:122:18
  11: main
  12: __libc_start_main
  13: _start

[2m2022-06-16T12:19:04.062938Z[0m [31mERROR[0m [2mveloren_voxygen[0m[2m:[0m VOXYGEN HAS PANICKED

A critical error has occurred and Voxygen has been forced to terminate in an unusual manner. Details about the error can be found below.

> What should I do?

We need your help to fix this! You can help by contacting us and reporting this problem. To do this, open an issue on the Veloren issue tracker:

https://www.gitlab.com/veloren/veloren/issues/new

If you're on the Veloren community Discord server, we'd be grateful if you could also post a message in the #support channel.
            
> What should I include?

The error information below will be useful in finding and fixing the problem. Please include as much information about your setup and the events that led up to the panic as possible.
            
Voxygen has logged information about the problem (including this message) to the file /home/marcelovbcfilho/.var/app/net.veloren.airshipper/data/airshipper/profiles/default/userdata/voxygen/logs/2022-06-16_voxygen.log. Please include the contents of this file in your bug report.
            
> Error information

The information below is intended for developers and testers.

Panic Payload: "called `Result::unwrap()` on an `Err` value: NoImplementation"
PanicInfo: panicked at 'called `Result::unwrap()` on an `Err` value: NoImplementation', voxygen/src/main.rs:154:22
Game version: b12dc3b0 [2022-06-08]

Backtrace:
   0: veloren_voxygen::main::{{closure}}
             at /builds/veloren/veloren/voxygen/src/main.rs:139:13
   1: std::panicking::rust_panic_with_hook
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/panicking.rs:142:14
   6: core::result::unwrap_failed
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/result.rs:1785:5
   7: core::result::Result<T,E>::unwrap
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/result.rs:1078:23
      veloren_voxygen::main::{{closure}}::{{closure}}
             at /builds/veloren/veloren/voxygen/src/main.rs:147:17
      veloren_voxygen::main::{{closure}}
             at /builds/veloren/veloren/voxygen/src/main.rs:171:13
   8: std::panicking::rust_panic_with_hook
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:702:17
   9: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:588:13
  10: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/sys_common/backtrace.rs:138:18
  11: rust_begin_unwind
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/panicking.rs:584:5
  12: core::panicking::panic_fmt
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/panicking.rs:142:14
  13: <wgpu::backend::direct::Context as wgpu::Context>::device_create_swap_chain
  14: veloren_voxygen::render::renderer::Renderer::new
             at /builds/veloren/veloren/voxygen/src/render/renderer.rs:350:26
  15: veloren_voxygen::window::Window::new
             at /builds/veloren/veloren/voxygen/src/window.rs:429:24
  16: veloren_voxygen::main
             at /builds/veloren/veloren/voxygen/src/main.rs:245:42
  17: core::ops::function::FnOnce::call_once
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/core/src/ops/function.rs:248:5
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/18f314e7027fe7084aaab8620c624a0d7bd29e70/library/std/src/sys_common/backtrace.rs:122:18
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by Frinksy** [comment]
Thanks for the report!
Your error seems to be related to issues [1567](https://gitlab.com/veloren/veloren/-/issues/1567) and [1547](https://gitlab.com/veloren/veloren/-/issues/1547) on the Veloren GitLab, so you may want to keep an eye on them too.
Issue 1547 is very much similar in that there is the same error in the logs: `2mgfx_backend_vulkan::device[0m[2m:[0m Unexpected result - driver bug? ERROR_INITIALIZATION_FAILED `.

I am reluctant to disable Wayland by default, as it works for at least some people (tested this myself on Fedora Silverblue 36, Intel iGPU). However thanks for reporting the fix too, it'll be useful for others who would need it, until the above mentioned issues are resolved in Veloren.

**Comment by rusty-snake** [comment]
Please don't downgrade security for everyone.

**Comment by LunarEclipse363** [comment]
Is this still an issue?

**Comment by charles-m-knox** [comment]
> Is this still an issue?

@LunarEclipse363  I think this is probably resolved, as I've heard plenty of reports that Wayland works fine and also I've personally verified that x11 works fine. Probably could close this.
