### ISSUE TITLE
Airshipper crashes on startup: X11 Error Bad Match

### ISSUE THREAD

**Issue by myrkvi** [flathub/net.veloren.airshipper#11]
Airshipper crashes on startup, running the flatpak installation

# System information
**OS:** Manjaro Linux x86_64
**Kernel:** 5.10.121-1-MANJARO
**Window Manager:** Qtile (X11)
**Graphics driver:** Nvidia 515.48.07-1

# Output
```term
[INFO] Loading Wayland library to get the current display
[INFO] Loading X11 library to get the current display
[INFO] Using default platform
[INFO] Display vendor "NVIDIA", version (1, 5)
[INFO] 	Trying native-render
[WARN] No config found!
[INFO] 	Trying presentation
[INFO] 	EGL context: +robust access
[INFO] 	EGL context: +surfaceless
[INFO] 	EGL surface: +srgb
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[INFO] Vendor: NVIDIA Corporation
[INFO] Renderer: NVIDIA GeForce GTX 960/PCIe/SSE2
[INFO] Version: OpenGL ES 3.2 NVIDIA 515.48.07
[INFO] SL version: OpenGL ES GLSL ES 3.20
[INFO] Private capabilities: PrivateCapabilities { flip_y_requires_shift: true, imageless_framebuffers: true, image_view_usage: true, timeline_semaphores: true, texture_d24: true, texture_d24_s8: true, non_coherent_map_mask: 63 }
[ERROR] X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
[ERROR] X11 error: XError {
    description: "BadMatch (invalid parameter attributes)",
    error_code: 8,
    request_code: 149,
    minor_code: 4,
}
[ERROR] Airshipper panicked:

Failed to translate window coordinates: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }: panicked at 'Failed to translate window coordinates: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }', /run/build/airshipper/cargo/vendor/winit/src/platform_impl/linux/x11/util/geometry.rs:290:18
thread 'main' panicked at 'Failed to translate window coordinates: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }', /run/build/airshipper/cargo/vendor/winit/src/platform_impl/linux/x11/util/geometry.rs:290:18
```

**Comment by Frinksy** [comment]
Apologies for the late reply, but does this issue still happen with the latest release?
If it does, you could try running Airshipper outside of the Flatpak sandbox to check if the issue is with Airshipper itself or the Flatpak package. You can grab the latest release binaries here: https://github.com/veloren/Airshipper/releases

**Comment by myrkvi** [comment]
Hi!

Airshipper v0.10.0 Flatpak from Flathub works fine :)
